const DATA = [
  {
    uid: "1234561",
    title: "Finance",
    desc: "crypto related ws",
    collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
    notes: ["NoteID1", "NoteID@3245"],
    todos: ["todoID@12434"],
    bookmarks: ["bmID@3410"],
  },
  {
    uid: "1234562",
    title: "School",
    desc: "crypto related ws",
    collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
    notes: ["NoteID1", "NoteID@3245"],
    todos: ["todoID@12434"],
    bookmarks: ["bmID@3410"],
  },
  {
    uid: "123453",
    title: "Reseach",
    desc: "crypto related ws",
    collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
    notes: ["NoteID1", "NoteID@3245"],
    todos: ["todoID@12434"],
    bookmarks: ["bmID@3410"],
  },
  // {
  //   title: "DSA",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },

  // {
  //   title: "Rent",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },
  // {
  //   title: "Movies",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },
  // {
  //   title: "Gas",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },
  // {
  //   title: "Somwthingf",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },
  // {
  //   title: "Finance",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },

  // {
  //   title: "Finance",
  //   desc: "crypto related ws",
  //   collaborators: ["harsh.ju.sharma@gmail.com", "test@gmail.com"],
  //   notes: ["NoteID1", "NoteID@3245"],
  //   todos: ["todoID@12434"],
  //   bookmarks: ["bmID@3410"],
  // },
];

export default DATA;
